---
date: "5/20/2021"
output: github_document
---

Colin Wick

This document serves as a clearing house for relevant portfolio items. I will be adding old assignments, work samples, and published items over time, with descriptions of each. Feel free to reach out for specific skill showcases or questions about the materials on this site at any time at colincwick@gmail.com.

### Full Writing Samples

[Data For Progress (Writing and research)](https://www.dataforprogress.org/memos/the-case-for-nationalizing-rural-hospitals). This published work demonstrates my ability to synthesize a number of primary source material and systemic analysis into a clear argument.

[Medicaid Event Study](https://github.com/ColinWick/MedicaidLabor/blob/main/Medicaid%20Expansion%20Effects%20on%20Labor%20Decisions.pdf) showcases my ability to formulate a question, build out a theoretical basis of analysis, and apply data cleaning and econometrics to CPS data to answer it. 

[Ideology and Identity](https://github.com/ColinWick/PublicOpinionML/blob/main/Ideology%20and%20Identity%20-%20Colin%20Wick.pdf) is intended as a showcase of applying machine learning tools to a dataset which does not necessarily lend itself to such methods.

```{r, include=FALSE,echo=FALSE,message=FALSE,eval=FALSE}
### Applied Assignments

ML 1

ML 2

ML 3

ML 4

Causal Replication

Metrics 1

Metrics 2

### Theory Assignments

Micro 2

Micro 3

Micro 6

Macro 1

### Assorted Small Projects
```